version: '3'
services:
  ranger-tagsync:
    build:
      context: .
      dockerfile: Dockerfile.ranger-tagsync
      args:
        - TAGSYNC_VERSION=${TAGSYNC_VERSION}
    image: ranger-tagsync
    container_name: ranger-tagsync
    hostname: ranger-tagsync.example.com
    stdin_open: true
    tty: true
    networks:
      - ranger
    depends_on:
      ranger:
        condition: service_started
    environment:
      - TAGSYNC_VERSION
      - DEBUG_TAGSYNC=${DEBUG_TAGSYNC:-false}
      - RANGER_POLICY_MGR_URL=http://ranger:6080
      - RANGER_TAGSYNC_PASSWORD=rangerR0cks!
    volumes:
      - ./scripts/reload_properties.sh:/reload_properties.sh
    command:
      - /reload_properties.sh /opt/ranger/tagsync/install.properties && /home/ranger/scripts/ranger-tagsync.sh

networks:
  ranger:
    name: rangernw
