version: '3'
services:
  ranger-usersync:
    build:
      context: .
      dockerfile: Dockerfile.ranger-usersync
      args:
        - USERSYNC_VERSION=${USERSYNC_VERSION}
    image: ranger-usersync
    container_name: ranger-usersync
    hostname: ranger-usersync.example.com
    stdin_open: true
    tty: true
    networks:
      - ranger
    depends_on:
      ranger:
        condition: service_started
    environment:
      - USERSYNC_VERSION
      - ENABLE_FILE_SYNC_SOURCE
      - DEBUG_USERSYNC=${DEBUG_USERSYNC:-false}
      - RANGER_POLICY_MGR_URL=http://ranger:6080
      - RANGER_USERSYNC_PASSWORD=rangerR0cks!
    volumes:
      - ./scripts/reload_properties.sh:/reload_properties.sh
    command:
      - /reload_properties.sh /opt/ranger/usersync/install.properties && /home/ranger/scripts/ranger-usersync.sh

networks:
  ranger:
    name: rangernw
