version: '3'
services:
  trino:
    build:
      context: .
      dockerfile: Dockerfile.ranger-trino
      args:
        - RANGER_VERSION=ranger-3.0.0-SNAPSHOT-trino-plugin
        - TRINO_VERSION=${TRINO_VERSION:-390}
    image: ranger-trino:${TRINO_VERSION:-390}
    hostname: ranger-trino
    container_name: ranger-trino
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    depends_on:
      ranger:
        condition: service_started
    networks:
      - ranger

networks:
  ranger:
    name: rangernw
